// Classes JavaScript File. There will be 10 classes with 5 spaces in each class.
let classes = [
    {
        "id": 1001,
        "title": "Maths",
        "location": "The Mathematics class will be held at Middlesex University in Room 11.",
        "price": 15,
        "image": "images/math.jpg",
        "availableSpaces": 5, // There will only be 5 spaces available as instructed 
    },
    {
        "id": 1002,
        "title": "English",
        "location": "The English class will be held at Middlesex University in Room 6.",
        "price": 10,
        "image": "images/english.jpg",
        "availableSpaces": 5, 
    },
    {
        "id": 1003,
        "title": "Art",
        "location": "The Arts and Crafts class will be held at Middlesex University in Room 1.",
        "price": 25,
        "image": "images/art.jpg",
        "availableSpaces": 5,  
    },
	{
        "id": 1004,
        "title": "Cooking",
        "location": "The Cooking class will be held at Middlesex University in Room 20.",
        "price": 10,
        "image": "images/cooking.jpg",
        "availableSpaces": 5, 
    },
	{
        "id": 1005,
        "title": "French",
        "location": "The French class will be held at Middlesex University in Room 7.",
        "price": 20,
        "image": "images/french.jpg",
        "availableSpaces": 5, 
    },
	{
        "id": 1006,
        "title": "Spanish",
        "location": "The Spanish class will be held at Middlesex University in Room 8.",
        "price": 20,
        "image": "images/spanish.jpg",
        "availableSpaces": 5,  
    },
	{
        "id": 1007,
        "title": "German",
        "location": "The German class will be held at Middlesex University in Room 9.",
        "price": 20,
        "image": "images/german.jpg",
        "availableSpaces": 5, 
    },
	{
        "id": 1008,
        "title": "Geogrpahy",
        "location": "The Geography class will be held at Middlesex University in Room 15.",
        "price": 15,
        "image": "images/geography.jpg",
        "availableSpaces": 5, 
    },
	{
        "id": 1009,
        "title": "History",
        "location": "The History class will be held at Middlesex University in Room 14.",
        "price": 15,
        "image": "images/history.jpg",
        "availableSpaces": 5, 
    },
	{
        "id": 1010,
        "title": "Physical Education",
        "location": "The Physical Education class will be held at Middlesex University in the Gym.",
        "price": 10,
        "image": "images/physicaleducation.jpg",
        "availableSpaces": 5,  
    },
]
